import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FinanceProvider } from "@/context/FinanceContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Theme script runs BEFORE any React code */}
        <Script
          id="theme-loader"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
                            (function() {
                                // Check for saved theme or system preference
                                const savedTheme = localStorage.getItem('theme');
                                const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                                
                                if (savedTheme === 'dark' || (!savedTheme && systemPrefersDark)) {
                                    document.documentElement.classList.add('dark');
                                } else {
                                    document.documentElement.classList.remove('dark');
                                }
                            })();
                        `
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <FinanceProvider>{children}</FinanceProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
